name: "monitoring"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  loki:
    image: "11notes/loki:3.6.7"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "loki.etc:/loki/etc"
      - "loki.var:/loki/var"
    ports:
      - "3000:3100/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  loki.etc:
  loki.var:

networks:
  frontend: